name: Build and release corkscrew
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        arch: [386, amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install autoconf mac
        if: matrix.os == 'macOS-latest'
        run: |
          export build=~/devtools # or wherever you'd like to build
          mkdir -p $build

          cd $build
          curl -OL http://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz
          tar xzf autoconf-2.69.tar.gz
          cd autoconf-2.69
          ./configure --prefix=/usr/local
          make
          sudo make install
          export PATH=$PATH:/usr/local/bin

          cd $build
          curl -OL http://ftpmirror.gnu.org/automake/automake-1.15.tar.gz
          tar xzf automake-1.15.tar.gz
          cd automake-1.15
          ./configure --prefix=/usr/local
          make
          sudo make install

          cd $build
          curl -OL http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
          tar xzf libtool-2.4.6.tar.gz
          cd libtool-2.4.6
          ./configure --prefix=/usr/local
          make
          sudo make install

          echo "Installation complete."
      - name: Linux Automake
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install autotools-dev automake wget gcc curl coreutils
      - name: Install curl
        if: matrix.os == 'windows-latest'
        run: |
          choco install curl
      - name: Set up Cygwin
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: flexdll cmake gcc-g++ make git gcc-core cygport binutils automake autoconf zip libtool autoconf gettext
          
    
      
      
      - name: Release windows-386
        if: matrix.os == 'windows-latest' && matrix.arch == '386'
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git clone https://github.com/bryanpkc/corkscrew
          cd corkscrew
          gcc -o corkscrew corkscrew.c
          

          $pwd = (pwd)
          curl -H "Authorization: token $env:MY_TOKEN" -H "Content-Type: application/octet-stream" -X POST https://uploads.github.com/repos/kelvinzer0/corkscrew/releases/89845666/assets?name=corkscrew-windows-386.exe --data-binary "@$pwd/corkscrew.exe"
    
          
      - name: Release windows-amd64
        if: matrix.os == 'windows-latest' && matrix.arch == 'amd64'
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git clone https://github.com/bryanpkc/corkscrew
          cd corkscrew
          gcc -o corkscrew corkscrew.c

         
         
      
          $pwd = (pwd)
          curl -H "Authorization: token $env:MY_TOKEN" -H "Content-Type: application/octet-stream" -X POST https://uploads.github.com/repos/kelvinzer0/corkscrew/releases/89845666/assets?name=corkscrew-windows-amd64.exe --data-binary "@$pwd/corkscrew.exe"
    
      - name: Release linux-386
        if: matrix.os == 'ubuntu-latest' && matrix.arch == '386'
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git clone https://github.com/bryanpkc/corkscrew
          cd corkscrew
          autoreconf --install
          ./configure
          make

          curl -H "Authorization: token ${MY_TOKEN}" -H "Content-Type: application/octet-stream" -X POST https://uploads.github.com/repos/kelvinzer0/corkscrew/releases/89845666/assets?name=corkscrew-linux-386 --data-binary @$(pwd)/corkscrew

      - name: Release linux-amd64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'amd64'
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git clone https://github.com/bryanpkc/corkscrew
          cd corkscrew
          autoreconf --install
          ./configure
          make

          curl -H "Authorization: token ${MY_TOKEN}" -H "Content-Type: application/octet-stream" -X POST https://uploads.github.com/repos/kelvinzer0/corkscrew/releases/89845666/assets?name=corkscrew-linux-amd64 --data-binary @$(pwd)/corkscrew

      - name: Release macos-386
        if: matrix.os == 'macOS-latest' && matrix.arch == '386'
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git clone https://github.com/bryanpkc/corkscrew
          cd corkscrew
          autoreconf --install
          ./configure
          make

          curl -H "Authorization: token ${MY_TOKEN}" -H "Content-Type: application/octet-stream" -X POST https://uploads.github.com/repos/kelvinzer0/corkscrew/releases/89845666/assets?name=corkscrew-macos-386 --data-binary @$(pwd)/corkscrew

      - name: Release macos-amd64
        if: matrix.os == 'macOS-latest' && matrix.arch == 'amd64'
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git clone https://github.com/bryanpkc/corkscrew
          cd corkscrew
          autoreconf --install
          ./configure
          make

          curl -H "Authorization: token ${MY_TOKEN}" -H "Content-Type: application/octet-stream" -X POST https://uploads.github.com/repos/kelvinzer0/corkscrew/releases/89845666/assets?name=corkscrew-macos-amd64 --data-binary @$(pwd)/corkscrew

